site_name: myMultivac Projects
site_url: https://github.mymultivac.com

nav: 
  - myMultivac: index.md
  - 'Projects':
    - 'Reflections': 'reflections.md'
    - 'Smartish Dots': 'smartish-dots.md'
    - 'Foundation': 'foundation.md'
    - 'Todo List Sync': 'pythonista-todo.md'
  - About: about.md
  
theme: 
  palette:
    scheme: default
    primary: blue
  logo: img/favicon.ico
  favicon: img/favicon.ico
  name: material
  custom_dir: overrides

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:website@mymultivac.com

copyright: Copyright &copy; 2021 - Ian Dionne

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - smarty
  - sane_lists

plugins:
  - search
  - mermaid2
  - macros
  - mkdocs-jupyter:
      execute: False
      include_source: True
