name: ci
on:
  push:
    remote:
      - Public
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin mkdocs-macros-plugin mkdocs-jupyter
      - run: mkdocs gh-deploy --force